### PR TITLE
add more whale facts

### PR DESCRIPTION
**Pull request by nguyendhse**
Hi, i just add more whale facts

### CODE REVIEW

**Comment by nguyendhse** [comment]
I updated the comma at the end, thanks to remind me

**Comment by mpentler** [comment]
Shit, one more thing. The facts need to work independent of seeing the others.

**Comment by mpentler** [comment]
There’s still a bit of a grammar check needed here I’m afraid.

**Comment by mpentler** [comment]
I like these facts a lot so I've decided I'm just going to fix it myself.

**Pull request merged**
