### PR TITLE
Add Ferrets to animal list

### PR DESCRIPTION
**Pull request by zara-nicole**

### CODE REVIEW

**Comment by mpentler** [comment]
@joel-g If we take #349 and ask @zara-nicole to put her changes into that new block, then these all look great! Ferrets are cute. People walk them on leads near me.

**Comment by mpentler** [comment]
@zara-nicole are you still around? I would love to add your facts to the Ferret block that we have now. Could you possibly redo your additions to fit that block and then I'll have a look at it? Thanks!

**Comment by zara-nicole** [comment]
Done!!

**Comment by mpentler** [comment]
Hooray for OCD!

**Comment by mpentler** [comment]
Finally ready to take! Sorry I messed you about on this :)

**Pull request merged**
