### PR TITLE
Added Bat Facts

### PR DESCRIPTION
**Pull request by Yusadolat**
Added Bat Facts

### CODE REVIEW

**Comment by syre** [comment]
https://github.com/syre/animal-facts-bot#how-to-contribute-teach-animalfactsbot-a-new-animal
"Don't add 'seal', 'bat' or 'duck' facts unless you've figured out how to not reply to homonyms."

**Comment by joel-g** [comment]
as @syre points out 'bat' facts can not be implemented at this time

**Comment by joel-g** [comment]
But I had an idea @Yusadolat , if you wanted to do update this to "fruit bat" or "vampire bat" facts that would work.

**Comment by Yusadolat** [comment]
@joel-g I will quickly work on Vampire bat now, Thanks

**Pull request closed without merging**
