### PR TITLE
Added bear facts and performed some small cleanup

### PR DESCRIPTION
**Pull request by starsky135**
As said in the title I've:

- Added various facts about bears
- Updated the README
- Added a trailing comma to the last fact in every fact tuple to make it easier for others to add facts
- Moved every fact tuple's parenthesis to a separate line per PEP8 to make it easier for people adding more facts and for consistency/clarity.

### CODE REVIEW

**Comment by starsky135** [comment]
Fixes #32.

**Comment by joel-g** [comment]
I like these changes but I'm having trouble with the merge conflicts. Github won't let me do it online and 
```git checkout -b starsky135-master master
curl -L https://github.com/joel-g/animal-facts-bot/pull/87.patch | git am -3``` isn't working, yet

**Comment by starsky135** [comment]
I'll have a go at resolving the conflicts in a few hours when I'm back on my PC.

**Comment by joel-g** [comment]
I'll take a break from reviewing pull requests. If you pull down the current master and merge on your end it should be easier for me to merge to master. I merged lots of other PR's before I got to yours

**Comment by starsky135** [comment]
I've created a new pull request which resolves all of the merge conflicts. It is the latest master with my added changes, so I'd encourage you to merge #128 before any others.

**Pull request closed without merging**
