### PR TITLE
Added Aardwolf Facts

### PR DESCRIPTION
**Pull request by FunctionalBarracuda**

### CODE REVIEW

**Comment by mpentler** [comment]
Shit sorry didn’t see the other PR

**Comment by mpentler** [comment]
@FunctionalBarracuda Oh, also do we need this PR still or can it all be done in the other one?

**Comment by mpentler** [comment]
Woops, deleted a comment. @FunctionalBarracuda are you around still?

**Comment by FunctionalBarracuda** [comment]
@mpentler I'm still around, but I don't know how to fix the problems you mentioned.

**Comment by mpentler** [comment]
Well, if this PR only has the README.md in then maybe we can close it and concentrate on the other one?

**Comment by mpentler** [comment]
Ok, sorry for the confusion @FunctionalBarracuda - took me a while to figure everything out.

I’ve taken your PR  for the fact additions, but for this one you’re definitely going to have to take the latest upstream and rebase. Mostly it’s about the capital letters on the animal list. 

Then we can take that one and Aardwolves are done :)

**Comment by mpentler** [comment]
Helloooo!?

**Comment by mpentler** [comment]
Wait I can fix this myself. Have made issue #375 for this and will close this PR now.

**Pull request closed without merging**
